### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by langestange** [mintystark/starkmenu#1]
All Programs Left pane:
Pane does not scroll to keep selected item visible.
Perhaps this is related to the broken scrolling, because the right pane behaviour is as expected.

Assumes that the list in the left pane is longer then the available vertical space.
Select top item eg All Applications
Use down arrow key to move the selection down.
As the selection moves past the last visible item in the list it disappears.
Normal behaviour would be for the list to scroll to ensure than the selected item is always visible.

Numpad Enter key:
It works in All Programs but not in Favourites or Quick Links.

Something else I've noticed:

Click to open the menu.
Do not select anything
Press the up arrow then Enter- the last item in All Applications list is activated.
Similarly, press the down arrow then Enter - the first item in All Apps list is activated.

Keep up the good work.

Regards

**Comment by mintystark** [comment]
Ok, I fixed the Category Scrollbar issues.  However some of the other issues are taking longer then I would like to spend on them. The other issues are also an issue with the Default Mint Menu.  The issue mainly comes from Tab selecting hidden items like the "Add to Panel" and "Add to Favorites" menus.  Then when you use the Arrow keys they move among the hidden items.  For now you can use the Tab key after the Super key to select the Favorites and the Quicklinks.  Unfortunately, I don't have any more time to look into it at the moment.  

For now I am going to Close this issue, but if you want you can separate out the other items and add them in there own Issue.  Then I will get back to them when I have time.
