### ISSUE TITLE
Missing shortcut

### ISSUE THREAD

**Issue by deekej** [mintystark/starkmenu#13]
Hello!

There is no option to set the key that we could use for opening the menu. E.g. pressing Super (meta/windows) key to open the menu and be able to immediately start writing in the search bar.

The default Cinnamon menu has it. Would it be possible to add it here?

Thank you!

**Comment by ghost** [comment]
hi,

problem with these shortcuts is that the way they get enabled change
between cinnamon version.

the menu isn't compatible to the standard menu at the moment.

regards bluedxca93
