### ISSUE TITLE
Scaling problemes with shutdown/logout and searchbar

### ISSUE THREAD

**Issue by ghost** [mintystark/starkmenu#4]
HI,
First of all  your applet is really great.
However, how can i modify the applet to prevent the folowing bug:
![bildschirmfoto vom 2014-02-03 17 24 58](https://f.cloud.github.com/assets/4351663/2066584/abf78cb8-8cf0-11e3-9780-9c21a906a557.png)

Another problem is the search menu. 
![bildschirmfoto vom 2014-02-03 17 39 45](https://f.cloud.github.com/assets/4351663/2066694/31730d8a-8cf2-11e3-9540-dc617cbe6db7.png)

I could solve bug 1 easily with settin an new Logout and Shutdown quicklink.

Bug 2 is really persistend

regards bluedxca93

**Comment by mintystark** [comment]
Well the first issue is a Theme issue.  The Theme is changing the button to be longer then its container.  Unfortunately, this is more a less an issue if the applet and theme not working well together.  If I had more time I would test the applet on as many Themes as I could.  Unfortunately, I don't.  So you might have to contact the Theme Developer to create a solution.

The second image is clear to me.  What is the issue with the search?  Could you provide more details.  Thanks

**Comment by ghost** [comment]
hi,
the white space down there. the search menu schould be expanded a bit when using menus-categories.
 btw the first bug could be "fixed" wit quicklinks so don´t worry about it to much. And I´ve developped this theme, and i can´t find the line in the source code where the error lies.)>=

**Comment by mintystark** [comment]
I see now, well I probably wont look into that as it will take up more time then I have, but it would be nice to do. Although since it is just for looks it is not really needed.
